label_mapping = {
    'Effusion': 1,
    'Emphysema': 2,
    'Atelectasis': 3,
    'Edema': 4,
    'Consolidation': 5,
    'Pleural_Thickening': 6,
    'Hernia': 7,
    'Mass': 8,
    'No Finding': 9,
    'Cardiomegaly': 10,
    'Nodule': 11,
    'Pneumothorax': 12,
    'Pneumonia': 13,
    'Fibrosis': 14,
    'Infiltration': 15,
}